// AUTO-GENERATED — do not edit by hand. Regenerate with apps/server/scripts/build-classification.mjs.
// Public NSE / AMFI sector taxonomy: ticker or fund name → [assetClass, sector, subSector].
import type { AssetClass } from "@dhan-drishti/core";

export type RefClass = [AssetClass, string, string];

/** Normalize a fund name so a broker export matches the reference (strip plan/option/legal words). */
export function normFund(name: string): string {
  return (name ?? "")
    .toUpperCase()
    .replace(/\b(DIRECT|REGULAR|PLAN|GROWTH|IDCW|DIVIDEND|PAYOUT|REINVEST|OPTION|FUND|SCHEME)\b/g, " ")
    .replace(/[^A-Z0-9]/g, "");
}

export const TICKER_CLASS: Record<string, RefClass> = {
  "AADHARHFC": ["equity","BFSI","FinServ"],
  "AARTIIND": ["equity","Chemicals","Chemicals"],
  "AARTIPHARM": ["equity","HealthCare","Pharma"],
  "AAVAS": ["equity","BFSI","FinServ"],
  "ABFRL": ["equity","Misc","Textiles"],
  "ACC": ["equity","Infra","Cement"],
  "ADANIPORTS": ["equity","Misc","Logistics"],
  "ALIVUS": ["equity","HealthCare","Pharma"],
  "ALPHA": ["etf","Index","LargeCap"],
  "ALPHAETF": ["etf","Index","LargeMid"],
  "ANGELONE": ["equity","BFSI","Misc"],
  "APLAPOLLO": ["equity","Infra","FinServ"],
  "APTECHT": ["equity","IT","IT"],
  "APTUS": ["equity","BFSI","FinServ"],
  "AXISBANK": ["equity","BFSI","Pvt Banks"],
  "BAJAJ-AUTO": ["equity","Auto","2Wh"],
  "BAJAJHFL": ["equity","BFSI","FinServ"],
  "BAJAJHIND": ["equity","Misc","Misc"],
  "BAJFINANCE": ["equity","BFSI","FinServ"],
  "BANKBEES": ["etf","Sectorial","Banks"],
  "BANKIETF": ["etf","Sectorial","Banks"],
  "BECTORFOOD": ["equity","FMCG","FMCG"],
  "BFSI": ["etf","Sectorial","BFSI"],
  "BHARTIARTL": ["equity","TeleCom","Telecom"],
  "BIRET": ["reit_invit","RealEstate","REIT"],
  "BLUEDART": ["equity","Misc","Misc"],
  "BSE": ["equity","BFSI","Misc"],
  "BSOFT": ["equity","IT","IT"],
  "BUILDPRO": ["equity","Misc","Constr"],
  "CAMS": ["equity","BFSI","ITFin"],
  "CANBK": ["equity","BFSI","PSU Banks"],
  "CANFINHOME": ["equity","BFSI","FinServ"],
  "CARERATING": ["equity","Misc","Misc"],
  "CDSL": ["equity","BFSI","Misc"],
  "CIEINDIA": ["equity","Auto","AutoAncy"],
  "CIPLA": ["equity","HealthCare","Pharma"],
  "COFORGE": ["equity","IT","IT"],
  "CONCOR": ["equity","Misc","Misc"],
  "CROMPTON": ["equity","CapitalGoods","CapitalGoods"],
  "DEEDEV": ["equity","Metal","Metal"],
  "DEEPAKNTR": ["equity","Chemicals","Fertilizers"],
  "DOLLAR": ["equity","Misc","Misc"],
  "EMBASSY": ["reit_invit","RealEstate","REIT"],
  "ETERNAL": ["equity","Misc","Misc"],
  "FEDERALBNK": ["equity","BFSI","Pvt Banks"],
  "FINIETF": ["etf","Sectorial","BFSI"],
  "GAIL": ["equity","Oil_Gas","Gas"],
  "GESHIP": ["equity","Misc","Misc"],
  "GNA": ["equity","Auto","AutoAncy"],
  "GOLDBEES": ["etf","Gold","Gold"],
  "GOODLUCK": ["equity","Metal","Metal"],
  "GPPL": ["equity","Misc","Misc"],
  "GSFC": ["equity","Chemicals","Fertilizers"],
  "HAL": ["equity","Defence","Defence"],
  "HAPPSTMNDS": ["equity","IT","IT"],
  "HCLTECH": ["equity","IT","IT"],
  "HDFCBANK": ["equity","BFSI","Pvt Banks"],
  "HDFCGOLD": ["etf","Gold","Gold"],
  "HDFCSILVER": ["etf","Silver","Silver"],
  "HDFCSML250": ["etf","Index","SmallCap"],
  "HEALTHY": ["etf","Sectorial","Misc"],
  "HINDCOPPER": ["equity","Metal","Metal"],
  "HINDPETRO": ["equity","Oil_Gas","Oil"],
  "HINDZINC": ["equity","Metal","Metal"],
  "HNGSNGBEES": ["etf","Global","Misc"],
  "ICICIBANK": ["equity","BFSI","Pvt Banks"],
  "ICICIGI": ["equity","BFSI","FinServ"],
  "IDFCFIRSTB": ["equity","BFSI","Pvt Banks"],
  "IGIL": ["equity","Misc","Misc"],
  "IGL": ["equity","Oil_Gas","Gas"],
  "INDGN": ["equity","HealthCare","Misc"],
  "INDIQUBE": ["equity","Misc","Misc"],
  "INDUSINDBK": ["equity","BFSI","Pvt Banks"],
  "INDUSTOWER": ["equity","TeleCom","Misc"],
  "INFY": ["equity","IT","IT"],
  "INOXWIND": ["equity","Energy","GreenEnergy"],
  "IOC": ["equity","Oil_Gas","Oil"],
  "ITBEES": ["etf","Sectorial","IT"],
  "ITC": ["equity","FMCG","FMCG"],
  "ITCHOTELS": ["equity","Hospitality","Hotel"],
  "J&KBANK": ["equity","BFSI","PSU Banks"],
  "JIOFIN": ["equity","BFSI","FinServ"],
  "JMFINANCIL": ["equity","BFSI","FinServ"],
  "JSWINFRA": ["equity","Infra","Misc"],
  "JUNIORBEES": ["etf","Index","Next50"],
  "KOTAKBANK": ["equity","BFSI","Pvt Banks"],
  "KRSNAA": ["equity","HealthCare","Diagnostics"],
  "LAURUSLABS": ["equity","HealthCare","Diagnostics"],
  "LIQUIDBEES": ["etf","Debt","Debt"],
  "LIQUIDCASE": ["etf","Debt","Debt"],
  "LT": ["equity","CapitalGoods","CapitalGoods"],
  "LTGILTBEES": ["etf","Debt","Debt"],
  "LUPIN": ["equity","HealthCare","Pharma"],
  "M&M": ["equity","Auto","4Wh"],
  "MAZDOCK": ["equity","Defence","Defence"],
  "MIDCAPETF": ["etf","Index","MidCap"],
  "MIDCAPIETF": ["etf","Index","MidCap"],
  "MINDSPACE": ["reit_invit","RealEstate","REIT"],
  "MODEFENCE": ["etf","Sectorial","Defence"],
  "MOMENTUM50": ["etf","Index","FlexiCap"],
  "MON100": ["etf","Global","Misc"],
  "MTARTECH": ["equity","Defence","Defence"],
  "NATCOPHARM": ["equity","HealthCare","Pharma"],
  "NETWEB": ["equity","IT","IT"],
  "NEWGEN": ["equity","IT","IT"],
  "NEXT50IETF": ["etf","Index","Next50"],
  "NH": ["equity","HealthCare","Hospital"],
  "NIFTYBEES": ["etf","Index","LargeCap"],
  "NTPC": ["equity","Energy","Power"],
  "NXST": ["reit_invit","RealEstate","REIT"],
  "OFSS": ["equity","IT","ITFin"],
  "ORIENTTECH": ["equity","IT","IT"],
  "PAYTM": ["equity","BFSI","ITFin"],
  "PERSISTENT": ["equity","IT","IT"],
  "PFC": ["equity","Energy","PowerFin"],
  "PGINVIT": ["reit_invit","Energy","Power"],
  "POLICYBZR": ["equity","BFSI","ITFin"],
  "POWERGRID": ["equity","Energy","Power"],
  "PREMIERENE": ["equity","Energy","GreenEnergy"],
  "PVTBANKADD": ["etf","Sectorial","Banks"],
  "RECLTD": ["equity","Energy","PowerFin"],
  "RELIANCE": ["equity","Oil_Gas","Misc"],
  "RPOWER": ["equity","Energy","Power"],
  "SBIFUNDS": ["equity","BFSI","FinServ"],
  "SBILIFE": ["equity","BFSI","Insurance"],
  "SBIN": ["equity","BFSI","PSU Banks"],
  "SGFIN": ["equity","BFSI","FinServ"],
  "SGMART": ["equity","Misc","Misc"],
  "SHAKTIPUMP": ["equity","Misc","Constr"],
  "SHANKARA": ["equity","Metal","Metal"],
  "SHAREINDIA": ["equity","BFSI","Misc"],
  "SILVERBEES": ["etf","Silver","Silver"],
  "SMALLCAP": ["etf","Index","SmallCap"],
  "STAR": ["equity","HealthCare","Pharma"],
  "STYRENIX": ["equity","Misc","Misc"],
  "SUDARSCHEM": ["equity","Chemicals","Chemicals"],
  "SUMICHEM": ["equity","Chemicals","Chemicals"],
  "SUNPHARMA": ["equity","HealthCare","Pharma"],
  "SYNGENE": ["equity","HealthCare","Pharma"],
  "TATAGOLD": ["etf","Gold","Gold"],
  "TATAPOWER": ["equity","Energy","Power"],
  "TATASTEEL": ["equity","Metal","Metal"],
  "TATATECH": ["equity","IT","IT"],
  "TATSILV": ["etf","Silver","Silver"],
  "TCS": ["equity","IT","IT"],
  "TECHM": ["equity","IT","IT"],
  "TRENT": ["equity","Misc","Misc"],
  "V2RETAIL": ["equity","FMCG","FMCG"],
  "VARROC": ["equity","Misc","Misc"],
  "VBL": ["equity","FMCG","FMCG"],
  "VESUVIUS": ["equity","Misc","Misc"],
  "ZENSARTECH": ["equity","IT","IT"],
};

export const FUND_CLASS: Record<string, RefClass> = {
  "ABSLMIDTERM": ["mf","Debt","Debt"],
  "ADITYABIRLASUNLIFEMEDIUMTERM": ["mf","Debt","Debt"],
  "AXISSMALLCAP": ["mf","SmallCap","Index"],
  "CANARAROBECOLARGEANDMIDCAP": ["mf","LargeMid","Index"],
  "CANROBLARGEMID": ["mf","LargeMid","Index"],
  "DSPSMALLCAP": ["mf","SmallCap","Index"],
  "HDFCFLEXI": ["mf","Flexi","Index"],
  "HDFCFLEXICAP": ["mf","Flexi","Index"],
  "ICICIPRUDENTIALAGGRESSIVEHYBRID": ["mf","Hybrid","Hybrid"],
  "ICICIPRUDENTIALEQUITYDEBT": ["mf","Hybrid","Hybrid"],
  "ICICIPRUDENTIALLARGEMIDCAP": ["mf","LargeMid","Index"],
  "ICICIPRUDENTIALSAVINGS": ["mf","Debt","Debt"],
  "ICICIPRUDENTIALULTRASHORTTOSHORTTERM": ["mf","Debt","Debt"],
  "ICICIPRUEQDEBT": ["mf","Hybrid","Hybrid"],
  "ICICIPRULARGEMID": ["mf","LargeMid","Index"],
  "ICICIPRUSAVINGS": ["mf","Debt","Debt"],
  "INVESCOINDIAINFRASTRUCTURE": ["mf","Sectorial","Infra"],
  "INVESCOINFRA": ["mf","Sectorial","Infra"],
  "JIOBLACKROCKFLEXICAP": ["mf","Flexi","Index"],
  "JIOBLACKROCKSECTORROTATION": ["mf","Sectorial","Misc"],
  "JIOBRFLEXI": ["mf","Flexi","Index"],
  "JIOBRSECTOR": ["mf","Sectorial","Misc"],
  "KOTAKMIDCAP": ["mf","MidCap","Index"],
  "MAELSS": ["mf","ELSS","ELSS"],
  "MAGRCONSU": ["mf","Sectorial","Consumer"],
  "MIRAEASSETELSSTAXSAVER": ["mf","ELSS","ELSS"],
  "MIRAEASSETGREATCONSUMER": ["mf","Sectorial","Consumer"],
  "PARAGPARIKHELSSTAXSAVER": ["mf","ELSS","ELSS"],
  "PARAGPARIKHFLEXICAP": ["mf","Flexi","Index"],
  "PPELSS": ["mf","ELSS","ELSS"],
  "PPFLEXI": ["mf","Flexi","Index"],
  "QUANTELSS": ["mf","ELSS","Index"],
  "QUANTELSSTAXSAVER": ["mf","ELSS","Index"],
  "SAMCOELSS": ["mf","ELSS","Index"],
  "SAMCOELSSTAXSAVER": ["mf","ELSS","Index"],
};
